# 一言でいうなら、コンテナ管理を設定

version: "3"
services:
  my-python-app:
    # build: . # このディレクトリ内でDockerイメージをビルド
    # # ↑ Dockerfileを呼び出してる！パスを明示でも行けるはず
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile

    volumes: # ホストとコンテナのディレクトリのマウントを記述する箇所
      - ../.dockervenv:/src/.venv # ホストの.dockerenvをコンテナの/src/.venvにマウント
      # ↑ dockervenv⇒コンテナの環境設定系を記述、venv⇒Pythonプロジェクトの仮想環構成を記述
      - ../:/src # カレントディレクトリを/srcにマウント
    ports:
      - "8000:8000" # ホストの8000をdockerの8000に接続
    environment: # 環境変数の設定場所
      - WATCHFILES_FORCE_POLLING=true # ホットリロード設定ON
